### ISSUE TITLE
Detecting deleted records

### ISSUE THREAD

**Issue by tomwrobel** [projectblacklight/blacklight_oai_provider#13]
Hi @bess 

Apologies if there is documentation for this, but I can't find it. We'd like to be able to inform downstream consumers of deletions: do you know how I would mark a record as deleted in Solr in a way that would appear in the blacklight_oai_provider?

Best wishes

Tom

**Comment by barmintor** [comment]
Hello,

This library has no way currently to do this - indeed, core Blacklight has no responsibility for creating or deleting Solr documents, it only assumes that it can read an existing index. You would need to handle this in your application.
