### ISSUE TITLE
Option to add new fields to Dublin Core Metadata

### ISSUE THREAD

**Issue by ashikajith** [projectblacklight/blacklight_oai_provider#14]
I'm trying add new fields in the Dublin Core Metadata (in my case `Editor`) but I am unable to find any documents or a way to add these fields and use along with the `field_semantics`. Going forward we are also planning to add more fields which does not include in the dublin core serialization fields.

**Comment by barmintor** [comment]
Adding non-dublin core fields is a programming task:
- Blacklight will filter the semantic fields to only those valid for Dublin Core Metadata in the dc export: `[:contributor, :coverage, :creator, :date, :description, :format, :identifier, :language, :publisher, :relation, :rights, :source, :subject, :title, :type]`, so to add an Editor field you would need to add a different export format (that is, a different subclass of `OAI::Provider::Metadata::Format`) with its own prefix (different from 'oai_dc', say for example 'new_metadata')
- your blacklight controller would need to register that `Format` subclass with its oai provider, probably by overriding the `oai_provider` method
- ruby-oai's OAIProvider implementation will expect the document model (usually SolrDocument in a blacklight app) to `record.respond_to?("to_#{prefix}")` where `prefix` is the export format... to follow the above, you would add a method to your SolrDocument model called `to_new_metadata` that returned XML
- your requests for OAI feed data would  need to pass the URL parameter `metadataPrefix=new_metadata`

It's not a terrible amount of work, but it is more than simple configuration.
