### ISSUE TITLE
Support on Blacklight 7

### ISSUE THREAD

**Issue by pghorpade** [projectblacklight/blacklight_oai_provider#18]
Hi,
I am trying to enable OAI-PMH on our hyrax application which uses blacklight 7.
Here is our Repo https://github.com/UCLALibrary/ursus
Can gem blacklight_oai_provider work with blacklight 7?
I added gem 'blacklight_oai_provider', '~> 6.0' to the gem file and ran bundle
I got errors :
bundle
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....
Bundler could not find compatible versions for gem "blacklight":
  In snapshot (Gemfile.lock):
    blacklight (= 7.0.1)

  In Gemfile:
    blacklight (~> 7.0.1)

    blacklight_oai_provider (~> 6.0) was resolved to 6.0.0, which depends on
      blacklight (~> 6.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

Also when I ran bundle update.

I got other errors:
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....
Bundler could not find compatible versions for gem "blacklight":
  In Gemfile:
    blacklight (~> 7.0.1)

    blacklight_oai_provider (~> 6.0) was resolved to 6.0.0, which depends on
      blacklight (~> 6.0)

Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (~> 5.1.6)

    blacklight (~> 7.0.1) was resolved to 7.0.1, which depends on
      rails (~> 5.1)

    blacklight_oai_provider (~> 6.0) was resolved to 6.0.0, which depends on
      rails (>= 4.2, < 6)

    blacklight_range_limit (~> 7.0.0) was resolved to 7.0.0, which depends on
      rails (>= 3.0)

Bundler could not find compatible versions for gem "sidekiq":
  In Gemfile:
    sidekiq (~> 5.2.7)

    capistrano-sidekiq (~> 0.20.0) was resolved to 0.20.0, which depends on
      sidekiq (>= 3.4)

**Comment by sandbergja** [comment]
I think the problem here is that there hasn't been a release of blacklight_oai_provider to rubygems.org since the blacklight 7 compatibility was added.

For example, I can get a basic blacklight 7 app to run with blacklight_oai_provider with just this line in my Gemfile:

`gem 'blacklight_oai_provider', github: 'projectblacklight/blacklight_oai_provider'`

**Comment by pghorpade** [comment]
thank you, this worked for me.
