### ISSUE TITLE
Another instance

### ISSUE THREAD

**Issue by rodyoukai** [projectblacklight/blacklight_oai_provider#19]
Hi,

Is there a way to create multiple instances of OAI with diferent mappings of metadata?

**Comment by barmintor** [comment]
It would not be a simple matter of configuration - you would have to do some Ruby work. There are a number of approaches you could use towards something like this:
- A second blacklight controller with a different solr document model
- A subresource with an OAI action on your current blacklight controller
- etc

The metadata mapping comes from your solr document model, so having different mappings would mean either having additional models or customizing your existing model to respond to some kind of contextual configuration.
