### ISSUE TITLE
Make oai endpoint pretty print configureable.

### ISSUE THREAD

**Issue by dkinzer** [projectblacklight/blacklight_oai_provider#21]
Is there a way to make the oai endpoint not use pretty print via stylesheet?

I tried adding an empty `app/assets/stylesheets/blacklight_oai_provider/oai2.xml` on my local but that didn't work.

I was forced to override the controller but it seems to me that this should be configurable.  If this is something others would be interested in, I could do a PR.

**Comment by barmintor** [comment]
Hey @dkinzer - I know this is a very old issue, but: Is there any chance that you added a file called `app/assets/stylesheets/blacklight_oai_provider/oai2.xml` and not `app/assets/stylesheets/blacklight_oai_provider/oai2.xsl`?

**Comment by barmintor** [comment]
I ask because I was able to add an identity transform at `app/assets/stylesheets/blacklight_oai_provider/oai2.xsl`:
```xml
<?xml version="1.0" ?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:template match="/ | @* | node()">
  <xsl:copy>
    <xsl:apply-templates select="@* | node()" />
  </xsl:copy>
  </xsl:template>
</xsl:stylesheet>
```

... and I am getting the unstyled response back from `/oai?verb=ListRecords&metadataPrefix=oai_dc`

**Comment by barmintor** [comment]
(obviously we might also propose a configuration under the oai key in the Blacklight config, but it seems desirable to go with a documentation-only solution if possible?)

**Comment by dkinzer** [comment]
@barmintor, that's exactly what happened.  😊 .  Thanks!

**Comment by barmintor** [comment]
Great! It might be worth adding this to the README.
