### ISSUE TITLE
Any plans to update for Rails 4 and/or Blacklight 5?

### ISSUE THREAD

**Issue by axemanyo10** [projectblacklight/blacklight_oai_provider#3]
Hi there,

I'd love to make use of this package, but I'm running Blacklight 5 (5.14.0) on Rails 4 (4.0.2) and it seems that this package will only work with Rails 3 (it has a dependency requirement "rails (~> 3.0)"). Is there any chance it could be updated for use with Rails 4?

Thanks,
Fergus.

**Comment by fereira** [comment]
I have the same requirements, though I'm using rails 4.1.6 and Blacklight 5.7.1

**Comment by barmintor** [comment]
@cgalarza check this out, maybe we should fork this repository and maybe work a PR up.

**Comment by cgalarza** [comment]
This thread is old, but I am working on a version of BlacklightOaiProvider that works with Blacklight 5 and Rails 4.

To install the release candidate add the following to your application's gemfile:
```
gem 'blacklight_oai_provider', '5.0.0.pre1'
```
And follow the installation and configuration instructions here:
https://github.com/projectblacklight/blacklight_oai_provider/tree/v5.0.0.pre1

If you run into and problems or have any feedback, reply to this thread.

**Comment by fereira** [comment]
Thanks for the update.  I've since created an api for exposing my repository but will give this a look as well.

**Comment by jrochkind** [comment]
I believe this is no longer relevant and the latest release works with Rails 4/5 and Blacklight 6?
