### ISSUE TITLE
Blacklight 7 support?

### ISSUE THREAD

**Issue by ta1986** [projectblacklight/blacklight_oai_provider#31]
My Blacklight was downgraded to 6.24.0 when I try to add the latest version of blacklight_oai_provider gem.
I see 7.x release listed in the README but could not find it. Could you show me how to check it out? Thanks.

**Comment by kevinpricethesecond** [comment]
Currently going through this process myself. I looked through the closed issues and came across [this thread](https://github.com/projectblacklight/blacklight_oai_provider/issues/18), which may help you.

**Comment by ta1986** [comment]
Thanks @kevinpricethesecond, turns out there is no 7.x release. Adding github repo to Gemfile works. Similar way to achieve this is checking out this project to local and add the following to Gemfile:

gem 'blacklight_oai_provider', :path => '/path/to/your/blacklight_oai_provider'
