### ISSUE TITLE
Create 7.0.x release/tag/gem and release-7.x branch for Blacklight 7

### ISSUE THREAD

**Issue by ryanfb** [projectblacklight/blacklight_oai_provider#32]
There should be a public 7.0.x release/tag/gem incorporating the recent changes to add Blacklight 7 support. See #17 which introduces version 7 and the need for a `release-7.x` branch. Cutting a 7.0.x gem on Rubygems (https://rubygems.org/gems/blacklight_oai_provider) would allow projects on Blacklight 7 to use versioned releases on Rubygems instead of pulling from GitHub (see #18 & #31).

**Comment by barmintor** [comment]
https://rubygems.org/gems/blacklight_oai_provider/versions/7.0.2
