### ISSUE TITLE
update faraday dependency?

### ISSUE THREAD

**Issue by jronallo** [projectblacklight/blacklight_oai_provider#4]
This gem relies on an older version of https://github.com/code4lib/ruby-oai which relies on faraday. This older version of faraday is preventing me from using osullivan in a long-lived Blacklight application. Would it be possible to update the faraday dependency here? Updating to the latest faraday here is probably the better solution to the issue I filed here: https://github.com/IIIF/osullivan/issues/57

It doesn't look like ruby-oai sets a version for faraday: https://github.com/code4lib/ruby-oai

**Comment by jrochkind** [comment]
Any thoughts on this?

**Comment by barmintor** [comment]
This was fixed in https://github.com/projectblacklight/blacklight_oai_provider/commit/62cf82bb056429fb888d750ec29252f3c23c0e72, but depends on a 7.x release (see #32)

**Comment by barmintor** [comment]
The relevant `oai` spec was backported to the 6.x line and released in 6.1, so I'm closing this ticket!
