### ISSUE TITLE
Merge fork?

### ISSUE THREAD

**Issue by electrickite** [projectblacklight/blacklight_oai_provider#5]
Ohio State University has done quite a bit of work on our fork of the Blacklight OAI gem: https://github.com/osulibraries/blacklight_oai_provider

In particular, the fork:
- Has been updated for Rails 4/Blacklight 6
- Adds set support
- Adds in a number of configuration points
- Fixes a few implementation errors in the underlying `oai` gem
- Improves test coverage

Is there any interest in merging these changes in to the gem? It's a fairly major overhaul, so I wanted to ask before submitting a PR.

**Comment by cgalarza** [comment]
@electrickite I think we'd be interested in using your fork at Columbia. We are still running Blacklight 5, but could spend sometime upgrading to Blacklight 6. Are there plans to merge in your fork? (Tagging @barmintor for thoughts/comments)

**Comment by barmintor** [comment]
I think we're about to be in the process of adding some maintainers to this repo who can evaluate the merge :)

**Comment by cgalarza** [comment]
Hurray!

**Comment by barmintor** [comment]
I'm looking at commit here, and it looks like it might be a little friendlier to try to cherrypick them over, so we can verify some interim stuff. I'm giving that a try, will post back here soon.

**Comment by jrochkind** [comment]
What is the status of this, I gather it has maybe been done?

**Comment by cgalarza** [comment]
It has. The fork could not be merged out right without losing support with BL 5, but I took a lot of inspiration from this fork.
